//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingMobile.Models.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DDH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DDH()
        {
            this.DDHCTs = new HashSet<DDHCT>();
        }
    
        public int MaDDH { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string TenNguoiNhan { get; set; }
        public string DiaChiNhan { get; set; }
        public Nullable<System.DateTime> NgayDH { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string SDT { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DDHCT> DDHCTs { get; set; }
    }
}
