//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingMobile.Models.ModelDB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DienThoai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DienThoai()
        {
            this.DDHCTs = new HashSet<DDHCT>();
        }
    
        public int MaDT { get; set; }
        [Display(Name ="Tên Điện Thoại")]
        public string TenDienThoai { get; set; }
        [Display(Name ="Giá")]
        public Nullable<decimal> Gia { get; set; }
        public string RAM_ROM { get; set; }
        public string Camera { get; set; }
        [Display(Name ="Trạng Thái")]
        public Nullable<bool> TrangThai { get; set; }
        [Display(Name ="Số lượng")]
        public Nullable<int> SoLuong { get; set; }
        [Display(Name ="Màn hình")]
        public string ManHinh { get; set; }
        public string TSKT { get; set; }
        [Display(Name ="Ảnh")]
        public string AnhDT { get; set; }
        public Nullable<int> MaHDT { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DDHCT> DDHCTs { get; set; }
        public virtual HangSanXuat HangSanXuat { get; set; }
        public virtual Image Image { get; set; }
    }
}
