//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingMobile.Models.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int MaDT { get; set; }
        public string Image_phu1 { get; set; }
        public string Image_phu2 { get; set; }
        public string Image_phu3 { get; set; }
    
        public virtual DienThoai DienThoai { get; set; }
    }
}
